import React from 'react';
import './CaosEvents.css';

// C.A.O.S. event lifecycle (v10.165) — pre-event (織り込み・大口の構え・シナリオ) and
// post-event (結果・大口/市場の捉え方・業界影響) prose, generated by the AI desk from
// C.A.O.S. + the realized reaction. Reported views, never trades; no fabricated numbers.
// Renders nothing when there are no analyses. Shown in the C.A.O.S. frame + Market Context.

interface CaosEvent {
  eventId: string; eventCode: string; phase: 'pre' | 'post';
  displayImpact: string; daysUntil: number | null; countdown?: string;
  headlineJa?: string; bodyJa: string; scenariosJa?: string[];
}

const IMPACT_JA: Record<string, string> = { critical: '重大', high: '大', medium: '中', low: '小' };
const PHASE: Record<string, { ja: string; tone: string }> = {
  pre: { ja: '発表前', tone: 'var(--event-high)' },
  post: { ja: '発表後', tone: 'var(--event-medium)' },
};

export const CaosEvents: React.FC<{ limit?: number }> = ({ limit }) => {
  const [items, setItems] = React.useState<CaosEvent[] | null>(null);
  React.useEffect(() => {
    const backend = import.meta.env.VITE_ARGUS_BACKEND_URL;
    if (!backend) return;
    let alive = true;
    const url = backend.replace(/\/$/, '') + '/api/argus/event-analysis';
    const load = () => fetch(url).then((r) => r.json()).then((j) => { if (alive) setItems(j.items || []); }).catch(() => {});
    load();
    const iv = setInterval(load, 5 * 60_000);   // refresh with the generation cadence
    return () => { alive = false; clearInterval(iv); };
  }, []);

  if (!items || items.length === 0) return null;
  const shown = limit ? items.slice(0, limit) : items;
  return (
    <section className="caose">
      <div className="caose-head">
        <span className="caose-title">C.A.O.S. · イベント分析</span>
        <span className="caose-sub">発表前=織り込み/シナリオ · 発表後=結果/大口・市場の捉え方</span>
      </div>
      {shown.map((it) => {
        const ph = PHASE[it.phase] ?? PHASE.pre;
        return (
          <div className="caose-row" key={it.eventId}>
            <div className="caose-l1">
              <span className="caose-phase" style={{ color: ph.tone, borderColor: ph.tone }}>{ph.ja}</span>
              <span className="caose-code">{it.eventCode}</span>
              <span className="caose-impact">影響:{IMPACT_JA[it.displayImpact] ?? it.displayImpact}</span>
            </div>
            {it.headlineJa && <div className="caose-headline">{it.headlineJa}</div>}
            <p className="caose-body">{it.bodyJa}</p>
            {it.scenariosJa && it.scenariosJa.length > 0 && (
              <ul className="caose-scn">{it.scenariosJa.map((s, i) => <li key={i}>{s}</li>)}</ul>
            )}
          </div>
        );
      })}
      <p className="caose-foot">機関の見解であり建玉ではない・数値は捏造しない。決定支援のみ。</p>
    </section>
  );
};
