import React from 'react';
import './CaosEvents.css';

// C.A.O.S. event lifecycle (v10.165, restructured v10.167) — compact headed one-liners
// per scheduled event: 概要 (always) / 事前予想 (pre only, omitted if empty) / 事後 (post
// only, never shown at the pre stage). Generated by the AI desk (GPT-5.5) from C.A.O.S. +
// the realized reaction. Reported views, never trades; no fabricated numbers. Renders
// nothing when there are no analyses. Sits beside the news — does NOT replace it.

interface CaosEvent {
  eventId: string; eventCode: string; phase: 'pre' | 'post';
  displayImpact: string; daysUntil: number | null; countdown?: string;
  summaryJa?: string; preJa?: string; postJa?: string;
  // legacy shape (pre-v10.167 cached items) — mapped onto 概要 so the panel never blanks.
  headlineJa?: string; bodyJa?: string; scenariosJa?: string[];
}

const IMPACT_JA: Record<string, string> = { critical: '重大', high: '大', medium: '中', low: '小' };
const PHASE: Record<string, { ja: string; tone: string }> = {
  pre: { ja: '発表前', tone: 'var(--event-high)' },
  post: { ja: '発表後', tone: 'var(--event-medium)' },
};

export const CaosEvents: React.FC<{ limit?: number }> = ({ limit }) => {
  const [items, setItems] = React.useState<CaosEvent[] | null>(null);
  React.useEffect(() => {
    const backend = import.meta.env.VITE_ARGUS_BACKEND_URL;
    if (!backend) return;
    let alive = true;
    const url = backend.replace(/\/$/, '') + '/api/argus/event-analysis';
    const load = () => fetch(url).then((r) => r.json()).then((j) => { if (alive) setItems(j.items || []); }).catch(() => {});
    load();
    const iv = setInterval(load, 5 * 60_000);   // refresh with the generation cadence
    return () => { alive = false; clearInterval(iv); };
  }, []);

  if (!items || items.length === 0) return null;
  const shown = limit ? items.slice(0, limit) : items;
  return (
    <section className="caose">
      <div className="caose-head">
        <span className="caose-title">C.A.O.S. · イベント分析</span>
        <span className="caose-sub">発表前=織り込み/シナリオ · 発表後=結果/大口・市場の捉え方</span>
      </div>
      {shown.map((it) => {
        const ph = PHASE[it.phase] ?? PHASE.pre;
        // 概要 always; fall back to the legacy headline/body for pre-v10.167 cached items.
        const summary = it.summaryJa || it.headlineJa || it.bodyJa || '';
        const pre = (it.preJa || '').trim();
        const post = (it.postJa || '').trim();
        return (
          <div className="caose-row" key={it.eventId}>
            <div className="caose-l1">
              <span className="caose-phase" style={{ color: ph.tone, borderColor: ph.tone }}>{ph.ja}</span>
              <span className="caose-code">{it.eventCode}</span>
              <span className="caose-impact">影響:{IMPACT_JA[it.displayImpact] ?? it.displayImpact}</span>
            </div>
            {summary && (
              <div className="caose-line"><span className="caose-h">概要</span><span className="caose-t">{summary}</span></div>
            )}
            {pre && (
              <div className="caose-line"><span className="caose-h caose-h--pre">事前予想</span><span className="caose-t">{pre}</span></div>
            )}
            {post && (
              <div className="caose-line"><span className="caose-h caose-h--post">事後</span><span className="caose-t">{post}</span></div>
            )}
          </div>
        );
      })}
      <p className="caose-foot">機関の見解であり建玉ではない・数値は捏造しない。決定支援のみ。</p>
    </section>
  );
};
