'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict'),Module=require('node:module'),ts=require('typescript');
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.React,esModuleInterop:true}}).outputText,f);
const React=require('react'),{renderToStaticMarkup}=require('react-dom/server');
let state={items:{},availability:{},loading:false,refreshFailed:false};
const load=Module._load;
Module._load=function(id,...args){if(id.endsWith('/useAnalystTargets'))return{useAnalystTargetState:()=>state};if(id.endsWith('/InstitutionalView'))return{InstitutionalView:()=>null};return load.call(this,id,...args);};
const root='../src/components/assetDesk/';
const {AssetDecisionDetails}=require(root+'AssetDecisionDetails.tsx'),{AssetTargetDetails}=require(root+'AssetTargetDetails.tsx'),{AssetScenarioPanel}=require(root+'AssetScenarioPanel.tsx'),{AssetFlowPanel}=require(root+'AssetFlowPanel.tsx'),{AssetEvidenceSummary}=require(root+'AssetEvidenceSummary.tsx'),{uniqueDetailText,detailTime}=require(root+'detailReading.ts');
Module._load=load;
const d={asset:{symbol:'1001',market:'JP'},genre:'jp',quote:{changePct:1.5,date:'2026-10-06'},decisionFirst:{symbol:'1001',currentActionJa:'WAIT',whyJa:'信用買い残が増えています。',nextJa:'次の公表を確認します。',whatChangesJa:'次の公表を確認します。',targets:[{value:'1,100',unit:'円'}],invalidation:{value:'900',unit:'円'},dataStatus:'前回値',dataState:'STALE',evidenceState:'STALE',asOf:'2026-10-06T06:30:00Z',nextCheck:'次の公表を確認します。'},strat:{bigFlowRatio:null,volume:120000,dataLimitations:['週次残高は未取得','週次残高は未取得'],scenarios:[]},sdg:{confidence:0.5,ownerReadableWhyJa:'信用残高を参照しています。',directnessJa:'直接データ',supplyDemandRank:'C',levelJa:'重い',evidence:{marginBuyingBalance:1200,marginSellingBalance:200,marginBalanceChange:{buyPct:2,sellPct:null}},ratios:{margin:6,jsf:0.7},sourceDates:{weeklyMargin:'2026-10-02',jsfDaily:'2026/10/06'},asOf:'2026-10-06T06:30:00Z'}};
const render=(C,patch={})=>renderToStaticMarkup(React.createElement(C,{d:{...d,...patch}}));
const overview=render(AssetDecisionDetails);
assert.equal((overview.match(/次の公表を確認します/g)||[]).length,1);
assert.ok(!overview.includes('WAIT')&&!overview.includes('いまの判断'));
assert.ok(overview.includes('記録・データ')&&overview.includes('前回値'));
assert.deepEqual(uniqueDetailText([' a 。','a。','b。','',null],['a。']),['b。']);
assert.equal(detailTime('2026-10-06T06:30:00Z'),'10/6 15:30');
assert.equal(detailTime('2026/10/02'),'2026/10/02');
const target={market:'JP',symbol:'1001',mean:1200,low:1000,high:1400,median:1250,analysts:8,source:'Yahoo Finance',fetchedAt:'2026-10-07T01:00:00Z',acquisitionStatus:'AVAILABLE'};
state.items={'JP:1001':target};
const targets=render(AssetTargetDetails);
assert.ok(targets.includes('1,000円〜1,400円')&&targets.includes('1,250円'));
assert.ok(targets.includes('アナリスト目標の内訳')&&targets.includes('ARGUSの参考水準'));
assert.ok(!targets.includes('1,200円'),'mean already appears on the initial card');
assert.ok(targets.includes('1,100')&&targets.includes('900'));
state.items={'JP:1001':{...target,low:Infinity,high:NaN,median:Infinity}};
assert.ok(!/Infinity|NaN/.test(render(AssetTargetDetails)));
state.refreshFailed=true;assert.ok(render(AssetTargetDetails).includes('保存した目標株価'));
assert.ok(!render(AssetTargetDetails,{genre:'us'}).includes('1,250円'),'market identity must match');
state={items:{},availability:{'JP:1001':{status:'NO_TARGET'}},loading:false,refreshFailed:false};
assert.ok(render(AssetTargetDetails).includes('集計がありません'));
const flow=render(AssetFlowPanel);
for(const v of ['信用倍率 6.00倍','日証金の貸借倍率 0.70倍','信用残 10/2週','日証金 10/6','売未取得','逆日歩 未取得'])assert.ok(flow.includes(v),v);
assert.ok(!flow.includes('需給ランク C'),'rank belongs to the initial card');
const evidence=render(AssetEvidenceSummary);
assert.ok(!evidence.includes('EVIDENCE STATE')&&evidence.includes('根拠の確認状況'));
assert.equal((evidence.match(/週次残高は未取得/g)||[]).length,1);
assert.ok(!evidence.includes('次の公表を確認します'),'overview already contains this check');
const scenarios=render(AssetScenarioPanel,{scn:{cases:[{label:'up',titleJa:'上向く場合',bandJa:'参考値',conditionsJa:['利益が増える']}],invalidationJa:['次の公表を確認します。','別の条件'],nextChecksJa:['別の条件','追加の確認']}});
assert.ok(scenarios.includes('利益が増える')&&scenarios.includes('追加の確認'));
assert.equal((scenarios.match(/別の条件/g)||[]).length,1);assert.ok(!scenarios.includes('次の公表を確認します'));
const types=require(root+'types.ts');assert.equal(types.tabForDeskSection('scenarios'),'chart');assert.equal(types.tabForDeskSection('flow-supply'),'evidence');
console.log('Expanded detail reading: dedupe, source separation, missing/saved states and navigation PASS');
