'use strict';
const fs = require('fs');
const ts = require('typescript');
const assert = require('node:assert/strict');
for (const ext of ['.ts', '.tsx']) require.extensions[ext] = (m, file) => m._compile(ts.transpileModule(fs.readFileSync(file, 'utf8'), {
  compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, jsx: ts.JsxEmit.React, esModuleInterop:true }
}).outputText, file);
const React = require('react');
const { renderToStaticMarkup } = require('react-dom/server');
const domain = require('../src/domain/assetOutlook.ts');
const { AssetOutlookSummary } = require('../src/components/assetDesk/AssetOutlookSummary.tsx');
const target = { market:'JP', symbol:'1001', mean:1200, analysts:8, currency:'JPY', fetchedAt:'2026-10-06T03:00:00Z', source:'Yahoo Finance', gapPct:99, priceAtFetch:500 };
assert.equal(domain.validAnalystTarget(target, 'JP:1001'), true);
for (const patch of [{ mean:NaN }, { analysts:-2 }, { analysts:1.2 }, { fetchedAt:'bad' }, { currency:'USD' }]) assert.equal(domain.validAnalystTarget({...target, ...patch}, 'JP:1001'), false);
assert.equal(domain.validAnalystTarget(target, 'US:1001'), false);
assert.equal(domain.analystTargetGap(target, 1000).toFixed(1), '20.0');
assert.equal(domain.analystTargetGap(target, null), null);
const supply = {market:'JP', supplyDemandRank:'C', conditionJa:'改善中だが信用買い残はまだ重い', directness:'direct_data', supplyDemandLevel:'very_heavy', levelJa:'かなり重い', sourceDates:{weeklyMargin:'2026-10-02',jsfDaily:'2026/10/06'}};
const render = patch => renderToStaticMarkup(React.createElement(AssetOutlookSummary, {market:'JP', target, currentPrice:1000, loading:false, refreshFailed:false, supply, ...patch}));
const html = render({});
for (const fact of ['1,200円','現在値比 +20.0%','8人','10/6取得','信用 10/2','日証金 10/6','かなり重い']) assert.ok(html.includes(fact), fact);
assert.ok(!html.includes('99.0%'));
assert.ok(render({refreshFailed:true}).includes('更新未確認・保存値'));
assert.ok(render({target:undefined,targetStatus:'NO_TARGET'}).includes('取得元に目標値なし'));
assert.ok(render({target:undefined,refreshFailed:true}).includes('取得未確認'));
assert.ok(!render({currentPrice:null}).includes('現在値比'));
assert.ok(render({supply:{...supply, directness:'stale_context', supplyDemandRank:'D'}}).includes('保存評価 D'));
assert.ok(render({supply:{...supply, market:'US'}}).includes('判定保留'));
assert.equal(render({market:'CRYPTO'}), '');
const summary = fs.readFileSync('src/components/assetDesk/AssetDecisionSummary.tsx', 'utf8');
assert.ok(summary.includes('<AssetOutlookSummary') && !summary.includes('gapPct.toFixed'));
const desk = fs.readFileSync('src/components/assetDesk/AssetDeskList.tsx', 'utf8');
assert.ok(desk.includes('sdBySym.get(`${a.market}:${sym}`)'));
console.log('Initial analyst/supply facts, current quote comparison, saved/missing states PASS');
