import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {chromium} from 'playwright';
const require=createRequire(import.meta.url),{build}=createRequire(require.resolve('vite/package.json'))('esbuild');
const web=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),now='2026-10-05T02:50:00Z';
const base={status:'AVAILABLE',instrumentId:'INDEX',returnPct:2.93,startDate:'2026-09-25',endDate:'2026-10-02'};
const internals={schemaVersion:'jp-market-internals-v1',asOfDate:'2026-10-02',evidenceId:'a'.repeat(64),actionAuthority:false,predictiveProbabilityVerified:false,limitationsJa:[],breadth:{status:'AVAILABLE',periodEnd:'2026-10-02',universeLabelJa:'東証プライム国内普通株',counts:{advancers:312,decliners:1305,unchanged:29,unavailable:0,totalUniverseCount:1646}},periods:{'5':{horizonSessions:5,startDate:base.startDate,endDate:base.endDate,index:base,benchmark:base,sectors:[{...base,instrumentId:'1623',nameJa:'鉄鋼・非鉄',returnPct:6.08,relativeToBenchmarkPct:6.11}],assets:[],sample:{isWholeMarket:false,counts:{advancers:0,decliners:0,unchanged:0,available:0,expected:0,missing:0}}}}};
const evidence={schemaVersion:'argus-decision-evidence-v1',generatedAt:now,subjects:{},marketView:{schemaVersion:'argus-jp-market-engine-market-view-v1',actionAuthority:false,informationCutoff:now,projection:{marketSignals:{signals:Array.from({length:7},(_,i)=>({id:`SIG-0${i+1}`,state:[2,3,4,7].includes(i+1)?'ACTIVE':'CLEAR',factNoteJa:`確認した条件の説明 ${i+1}`}))}},sourceStatus:{},internals}};
const marginDynamics={schemaVersion:'jp-market-dynamics-v1',instrumentId:'1570',balanceKind:'WEEKLY_MARGIN',actionAuthority:false,observedCoveringOrders:false,predictiveProbability:null,current:{periodEnd:'2026-09-25',unit:'UNITS',longBalance:1000,shortBalance:100,ratio:10},previous:{periodEnd:'2026-09-18',unit:'UNITS',longBalance:1200,shortBalance:80,ratio:15},change:{status:'AVAILABLE',longContribution:-2.25,shortContribution:-2.75,ratioChange:-5,longBalanceChange:-200,shortBalanceChange:20,isOneWeekChange:true},lastSuccessfulAcquisitionAt:now,acquisitionStatus:'AVAILABLE',sourceStatus:'AVAILABLE',sourceRows:[{periodEnd:'2026-10-01',seriesId:'margin.long_balance',value:1050,unit:'UNITS'},{periodEnd:'2026-10-01',seriesId:'margin.short_balance',value:90,unit:'UNITS'}]};
const jpyPosition={schemaVersion:'jp-market-jpy-position-v1',status:'AVAILABLE',instrumentId:'JPY',contractCode:'097741',contractSizeJpy:12500000,reportType:'LEGACY_FUTURES_ONLY',traderCategory:'NON_COMMERCIAL',unit:'CONTRACTS',actionAuthority:false,observesCurrentLivePositions:false,positionDate:'2026-09-29',previousPositionDate:'2026-09-22',receivedAt:now,publishedAt:null,positionAgeCalendarDays:6,current:{longContracts:100,shortContracts:90,spreadContracts:5,netContracts:10},previous:{longContracts:95,shortContracts:92,spreadContracts:6,netContracts:3},change:{longContracts:5,shortContracts:-2,spreadContracts:-1,netContracts:7},sourceRef:'https://www.cftc.gov/dea/futures/deacmesf.htm'};
evidence.marketView.margin1570Dynamics=marginDynamics;evidence.marketView.jpyPosition=jpyPosition;
const macro={eventId:'auction-10',displayEventId:'auction-10',dedupeKey:'auction-10',eventCode:'AUCTION',title:'US Treasury 10-Year Auction',eventDate:'2026-10-07',importance:'high',state:'pre',stateLabelJa:'発表前',officialResult:{available:false},caos:{preScenarioJa:'入札の需要が弱ければ金利上昇が株の重しになります。'},display:{showPreProminently:true}};
const dashboard={schemaVersion:'dashboard-event-summary-v1',asOf:now,items:[macro],status:{},dedupe:{mergedCount:0,hiddenDuplicateCount:0,detailsJa:[]}};
const calendar={schemaVersion:'jp-equity-event-calendar-v1',asOf:now,status:'AVAILABLE',rangeStart:'2026-10-05',rangeEnd:'2026-11-19',gaps:[],automaticAiCalls:0,actionAuthority:false,dependsOnAi:false,events:[{eventId:'jp-monthly-sq-2026-10',kind:'SQ',at:'2026-10-09T08:45:00+09:00',dateOnly:false,date:'2026-10-09',daysUntil:4,titleJa:'SQ（日経225先物・オプションの清算）',importance:'medium',whatJa:'清算日です。',soWhatJa:'前日から当日朝にかけて値が振れやすくなります。',watchJa:'寄付きの値動きを確認します。',source:'JPX',actionAuthority:false}]};
const sectors={schemaVersion:'jp-sector-heatmap-v1',targetDate:'2026-10-05',isToday:true,session:{session:'MORNING_SESSION'},collectionErrors:{},rows:['自動車・輸送機','電機・精密','銀行','商社・卸売','情報通信・サービス','医薬品','電力・ガス','不動産'].map((nameJa,i)=>({symbol:String(1620+i),nameJa,state:'AVAILABLE',sourceTimestamp:now,source:'検査用データ',periods:{'1':{startDate:'2026-10-02',endDate:'2026-10-05',returnPct:i%2?2:-.4,relativeToBenchmarkPct:i%2?1:-1}}}))};
const metric={evaluated:40,falls:16,fallShare:.4,fallShareWilsonLower95:.3,riseShare:.6,meanReturnPct:.2,baselineSessions:900,baselineFallShare:.5,baselineMeanReturnPct:.1,hits:24,hitShare:.6,hitShareWilsonLower95:.45,baselineHitShare:.5};
const signStudy={schemaVersion:'jp-sign-event-study-v1',method:'検査用',informationCutoff:now,status:'AVAILABLE',cooldownSessions:20,horizons:[5],primaryHorizon:5,minimumActivations:20,historicalVintageVerified:false,validationStatus:'UNVALIDATED',predictiveProbabilities:null,actionAuthority:false,conditions:Object.fromEntries(Array.from({length:7},(_,i)=>{const family=`D0${i+1}`,na=i===6;return [family,{family,expects:na?null:[0,1,3].includes(i)?'FALL':'RISE',status:na?'NOT_EVALUABLE':'NOT_ABOVE_BASELINE',rawActivations:na?0:42,activations:na?0:40,overlappingMerged:na?0:2,firstActivation:na?null:'2017-01-05',lastActivation:na?null:'2026-09-25',coverageStart:'2016-10-04',coverageEnd:'2026-09-25',horizons:na?{}:{5:metric},falseAlarms:0,falseAlarmShare:na?null:0,periods:na?[]:['design','confirm','report'].map(name=>({name,start:'2017-01-05',end:'2026-09-25',activations:40,horizons:{5:metric}})),predictiveProbabilities:null,actionAuthority:false}]}))};
const comparison={schemaVersion:'jp-market-comparison-v1',informationCutoff:now,anchorDate:'2026-10-02',actualAnchorPrice:40000,unit:'ANCHOR_100',actual:[{offsetSessions:0,value:100}],candidates:[],forecast:{status:'INSUFFICIENT_COMPLETE_ANALOGS',line:[],band:[],horizonSessions:5,validationStatus:'UNVALIDATED',sampleCount:0,counts:{up:0,flat:0,down:0},flatThresholdPct:.5,signEventStudy:signStudy},scaleExplanation:'検査用',limitations:['未検証']};
const fixture=await build({stdin:{contents:`import React from 'react';import {createRoot} from 'react-dom/client';import {AssetsProvider} from './src/hooks/useAssets';import {ArgusTodayPanel} from './src/components/today/ArgusTodayPanel';import {buildArgusTodayView} from './src/domain/argusTodayView';
const c={schemaVersion:'single-decision-authority-v2',decisionId:'sda-'+ '1'.repeat(64),status:'DATA_GATED',primaryAction:'WAIT',confidence:{valueBps:null,status:'UNAVAILABLE'},targets:[],invalidation:null,nextReviewConditionCodes:['evidence_refresh'],freshness:'UNKNOWN',missingReasonCodes:['quality_missing'],conflictReasonCodes:[],dissentReasonCodes:[],evidenceRefs:[],primitiveFactorIds:[],guidance:{position:'NO_ACTION',riskConstraint:'WAIT_REQUIRED'},identities:{authorityPolicyId:'argus-single-decision-authority-v2',marketTruth:{status:'MISSING'},predictionLedger:{status:'MISSING'},jp_market_engine:{status:'MISSING'},risk:{status:'DATA_GATED'}},sevenSign:{status:'DATA_GATED',candidateLevel:null,productionLevel:null,reasonCodes:['decision_data_gated']}};
const view=buildArgusTodayView({now:new Date('${now}'),selectionMode:'JP',dataQuality:'PARTIAL',canonicalDecision:c,calendar:{},events:[]});view.dataQualityReasonCodes=['watchlist_polling_partial','quote_authority_missing'];createRoot(document.getElementById('root')).render(<AssetsProvider><ArgusTodayPanel view={view} selectedSymbol="1321" horizon={5} projectionSource={null} freshnessNoteJa={null} chartLoad={{loading:false,loaderVisible:false,slowInitial:false,statusText:'',error:null,snapshotState:'CURRENT_READY',snapshotId:'test',responseSnapshotId:'test',retry:()=>{}}} shock={{status:'data',events:[]}} newsIntel={{status:'data',events:[]}} onNavigate={()=>{}} aiButton={null}/></AssetsProvider>);`,loader:'tsx',resolveDir:web},bundle:true,write:false,format:'iife',platform:'browser',loader:{'.css':'empty'},define:{'import.meta.env.VITE_ARGUS_BACKEND_URL':JSON.stringify('https://reading.test'),'import.meta.env.VITE_ARGUS_OWNER_AUTH_REQUIRED':JSON.stringify('0'),'process.env.NODE_ENV':JSON.stringify('development')},logLevel:'silent'});
const browser=await chromium.launch({headless:true});
try{for(const width of [320,390,1280]){
 const page=await browser.newPage({viewport:{width,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install({time:new Date(now)});
 await page.route('https://reading.test/**',r=>{const pathname=new URL(r.request().url()).pathname;const data=pathname.includes('decision-evidence')?evidence:pathname.endsWith('sector-heatmap')?sectors:pathname.endsWith('dashboard-events')?dashboard:pathname.endsWith('jp-equity-calendar')?calendar:pathname.endsWith('index-chart')?{status:'available',actionAuthority:false,automaticAiCalls:0,comparison,lastSuccessfulAcquisitionAt:now}:null;
 return pathname==='/'?r.fulfill({contentType:'text/html',body:'<div id="root"></div>'}):data?r.fulfill({json:data}):r.fulfill({status:503,json:{error:'検査用の未取得状態'}});});
 await page.goto('https://reading.test/');await page.addStyleTag({content:['src/styles/theme.css','src/components/today/ArgusToday.css','src/components/today/ReadingHierarchy.css','src/components/today/SectorHeatmap.css','src/components/dashboard/ImportantEventsCard.css'].map(p=>fs.readFileSync(path.join(web,p),'utf8')).join('\n')+'html,body,#root{height:auto;overflow:visible}body{margin:0;padding:16px;background:var(--bg);color:var(--text-main);font-family:system-ui}#root{max-width:850px;margin:auto}.card{background:var(--surface);border:1px solid var(--line);border-radius:14px}button{font-family:inherit}'});
 await page.addScriptTag({content:fixture.outputFiles[0].text});
 try{await page.locator('[data-market-signals-active="4"]').waitFor({timeout:8000});}catch(error){throw new Error(JSON.stringify({errors,body:(await page.locator('body').innerText()).slice(0,1800)}),{cause:error});}
 assert.equal(await page.locator('.at-seven').getAttribute('open'),'');assert.equal(await page.locator('.at-seven-condition:visible').count(),7);assert.equal(await page.locator('.at-seven-fact:visible').count(),7);assert.equal(await page.locator('.at-seven-rule:visible').count(),7);assert.match(await page.locator('[data-signal-id="SIG-02"]').innerText(),/2 · 日経レバの制度信用倍率/);assert.match(await page.locator('[data-signal-id="SIG-04"]').innerText(),/4 · 日経平均の割高・割安（PER）/);
 assert.equal(await page.locator('[data-argus-contract="market-signals-top-v1"]').innerText(),'成立している条件 4件');assert.equal(await page.locator('.at-seven-direction[data-direction="warning"]:visible').count(),3);assert.equal(await page.locator('.at-seven-direction[data-direction="support"]:visible').count(),4);assert.equal(await page.locator('.at-seven-performance:visible').count(),7);assert.match(await page.locator('.at-seven-signals').innerText(),/原典との照合待ち/);await page.locator('.at-seven-study-time').waitFor();assert.match(await page.locator('[data-signal-id="SIG-06"] .at-seven-performance').innerText(),/上昇 60.0%（普段 50.0%）・40件・基準を上回らない/);assert.match(await page.locator('[data-signal-id="SIG-07"] .at-seven-performance').innerText(),/測定規則なし/);assert.equal(await page.locator('.at-decision-details').getAttribute('open'),null);assert.equal(await page.locator('.at-decision-status').innerText(),'現在の判断：見送り');assert.equal(await page.locator('.at-data-summary li').count(),2);
 assert.equal(await page.locator('.te-title h4').count(),1);assert.equal(await page.locator('.ie-code:visible').count(),0);assert.equal(await page.locator('.ie-title-ja:visible').innerText(),'米10年債入札');assert.equal(await page.locator('.ie-peek:visible').count(),1);
 await page.locator('.ie-row--reading > summary').click();assert.equal(await page.locator('.ie-phase:visible').count(),1,'発表前に空の結果・発表後欄を出さない');
 assert.equal(await page.locator('.sector-heatmap__legend').count(),0);assert.equal(await page.locator('.sector-heatmap__grid button:visible').count(),8);assert.ok((await page.locator('.at-internals').innerText()).includes('集計期間が異なります'));
 assert.match(await page.locator('[aria-label="日経レバの信用需給"] .at-context-lead').innerText(),/買い残が減り、売り残は増えています/);assert.equal(await page.locator('[data-margin-daily]').innerText().then(v=>v.includes('11.67')),true);assert.match(await page.locator('[aria-label="円の投機ポジション"] .at-context-lead').innerText(),/円買いの偏りが拡大/);
 assert.equal(await page.locator('.at-seven-rule').evaluateAll(rows=>rows.every(el=>el.scrollWidth<=el.clientWidth+1)),true,'every condition remains readable inside its card');
 assert.equal(await page.locator('.at-context').getAttribute('open'),null);assert.equal(await page.locator('.at-context .at-marketview:visible').count(),0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);assert.deepEqual(errors,[]);
 if(process.env.DECISION_UI_EVIDENCE_DIR){fs.mkdirSync(process.env.DECISION_UI_EVIDENCE_DIR,{recursive:true});for(const [selector,name] of [['.at-primary-hero','conditions'],['#today-events','events'],['.at-internals','internals'],['[aria-label="日経レバの信用需給"]','margin'],['[aria-label="円の投機ポジション"]','jpy']])await page.locator(selector).screenshot({path:path.join(process.env.DECISION_UI_EVIDENCE_DIR,name+'-'+width+'.png')});}
 await page.close();
}console.log('判断の読み方：320/390/1280pxで7条件、発表前の予定、期間の区別、重複の折り畳み、横幅を確認');}finally{await browser.close()}
