const assert = require('node:assert/strict'), Module = require('node:module'), path = require('node:path'), esbuild = require('esbuild');
// Supply browser state explicitly on every Node runtime used by CI.
const browserNavigator = {onLine: true};
Object.defineProperty(globalThis, 'navigator', {configurable: true, value: browserNavigator});
const calls = [], listeners = {}; const serverToken = 'x'.repeat(43); let pending;
const original = async (request) => {
  calls.push(request);
  const headers = {'X-ARGUS-OWNER-NONCE': request.headers.get('X-ARGUS-OWNER-NONCE') ?? ''};
  if (request.url.endsWith('/password')) return Response.json({token: serverToken, expiresAt: Date.now() + 1800000});
  if (request.url.endsWith('/logout')) return Response.json({loggedOut: true}, {headers});
  if (request.url.endsWith('/slow')) return new Promise(resolve => { pending = resolve; });
  return Response.json({ok: true, authenticated: true}, request.url.endsWith('/old-cache') ? {} : {headers});
};
global.window = {fetch: original, location: {origin: 'https://owner.example'}, setInterval: () => 1, addEventListener: (n, f) => { listeners[n] = f; }};
global.document = {hidden: false, addEventListener: (n, f) => { listeners[n] = f; }};
const entry = path.resolve('src/lib/ownerSession.ts');
const code = esbuild.buildSync({entryPoints: [entry],bundle: true,write: false,platform: 'node',format: 'cjs', define: {'import.meta.env': JSON.stringify({VITE_ARGUS_OWNER_AUTH_REQUIRED: '1', VITE_ARGUS_BACKEND_URL: 'https://api.example'})},logLevel:'silent'}).outputFiles[0].text;
const mod = new Module(entry,module); mod.filename=entry;mod.paths=module.paths;mod._compile(code,entry);
const api=mod.exports; api.installOwnerTransport(); global.fetch=window.fetch;
(async () => {
  await assert.rejects(fetch('https://api.example/api/argus/data'), /owner_auth_required/); assert.equal(calls.length, 0);
  await api.passwordLogin('fixture-password'); assert.equal(api.hasOwnerSession(), true);
  await fetch('https://api.example/api/argus/data', {headers: {'X-Preserved': 'value'}});
  assert.equal(calls.at(-1).headers.get('X-ARGUS-OWNER-SESSION'), serverToken);
  assert.equal(calls.at(-1).headers.get('X-Preserved'), 'value');
  assert.equal(calls.at(-1).redirect, 'error'); assert.equal(calls.at(-1).cache, 'no-store');
  await fetch('https://elsewhere.example/api/data'); assert.equal(calls.at(-1).headers.has('X-ARGUS-OWNER-SESSION'), false);
  await fetch('https://api.example.evil.example/api/data'); assert.equal(calls.at(-1).headers.has('X-ARGUS-OWNER-SESSION'), false);
  const slow = fetch('https://api.example/api/argus/slow'); await api.logoutOwner();
  assert.equal(api.hasOwnerSession(), false); assert.equal(calls.at(-1).headers.get('X-ARGUS-OWNER-SESSION'), serverToken);
  pending(Response.json({secret: 'old-response'})); await assert.rejects(slow, /owner_session_changed/);
  await api.passwordLogin('fixture-password');
  await assert.rejects(fetch('https://api.example/api/argus/old-cache'), /owner_response_unverified/);
  assert.equal(api.hasOwnerSession(), false);
  await api.passwordLogin('fixture-password'); listeners.pagehide(); assert.equal(api.hasOwnerSession(), false);
  browserNavigator.onLine = false;
  await assert.rejects(api.passwordLogin('fixture-password'), /authentication_cancelled/);
  assert.equal(api.hasOwnerSession(), false);
  browserNavigator.onLine = true;
  await api.passwordLogin('fixture-password');
  listeners.offline(); assert.equal(api.hasOwnerSession(), false);
  console.log('Owner transport: locked requests, exact origin, preserved headers, no-store, no redirects, logout and stale response isolation PASS');
})().catch(error => {api.clearOwnerSession(); console.error(error);process.exit(1);});
