const assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
require.extensions['.ts']=(mod,file)=>mod._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,file);
const {todayEventSchedule}=require('../src/lib/todayEventSchedule.ts');
const now=Date.parse('2026-10-05T09:00:00+09:00');
const macro=(code,date,title,state='pre')=>({eventId:`${code}-${date}-${title}`,displayEventId:`${code}-${date}-${title}`,eventCode:code,eventDate:date,eventTimeUtc:null,title,state,importance:'high',officialResult:{available:false},caos:{},display:{}});
const legacy=(code,date,title)=>({eventId:`legacy-${code}-${date}`,eventCode:code,date,title,displayImpact:'high',lifecycle:'SCHEDULED'});
const equity=(kind,date)=>({eventId:`jp-${kind}-${date}`,kind,date,at:date,dateOnly:true,titleJa:kind,daysUntil:4});
const d=[macro('CPI','2026-10-14','US CPI'),macro('AUCTION','2026-10-07','US Treasury 10-Year Auction'),macro('NFP','2026-10-02','US Employment Situation','post_result')];
const l=[legacy('CPI','2026-10-14','US CPI'),legacy('CPI','2026-11-13','US CPI'),legacy('AUCTION','2026-10-07','US Treasury 30-Year Auction'),legacy('SQ','2026-10-09','SQ')];
const e=[equity('SQ','2026-10-09'),equity('SQ','2026-11-13'),equity('JP_CPI','2026-10-23')];
const before=JSON.stringify([d,l,e]);const rows=todayEventSchedule(d,l,e,now);
assert.equal(rows.filter(r=>r.day==='2026-10-14'&&r.event.eventCode==='CPI').length,1);
assert.equal(rows.filter(r=>r.day==='2026-10-07').length,2,'different bond maturities stay separate');
assert.equal(rows.filter(r=>r.day==='2026-10-09').length,1,'SQ appears once across calendars');
assert.equal(rows.filter(r=>r.day==='2026-11-13').length,2,'a later CPI and SQ remain');
assert.equal(rows[0].day,'2026-10-07');assert.equal(rows.at(-1).event.eventCode,'NFP');assert.equal(rows.at(-1).released,true);
assert.equal(JSON.stringify([d,l,e]),before,'sorting never mutates canonical feeds');
const boundary=macro('FOMC','2026-10-28','FOMC');boundary.eventTimeUtc='2026-10-28T18:00:00Z';
assert.equal(todayEventSchedule([boundary],[],[],now)[0].day,'2026-10-29','uses Japan date, not UTC date');
assert.equal(todayEventSchedule([],[],[equity('JP_CPI','2026-11-20')],now).length,0,'45-day window stays exact');
const aged=macro('NFP','2026-09-01','US Employment Situation','post_result');
assert.equal(todayEventSchedule([aged],[],[],now).length,0,'old releases do not reappear');
const undated={...macro('CPI',null,'US CPI'),eventDate:null};
assert.equal(todayEventSchedule([undated],[],[],now).length,1,'unconfirmed date is not silently lost');
const early={...legacy('CPI','2026-10-14','US CPI'),jstTime:'2026-10-14 08:30 JST'},late={...legacy('PPI','2026-10-14','US PPI'),jstTime:'2026-10-14 21:30 JST'};
assert.equal(todayEventSchedule([], [late,early], [], now)[0].event.eventCode,'CPI','same-day events use the published Japan time');
console.log('日付順の予定：重複除去・別の開催日・日本時間・45日・発表結果・元データ保持を確認');
